#No specific path WRITING
##testFile = open("text.txt", "w")
##testFile.write("Michael Dave Sumang")
##testFile.close()

#Specific path WRITING
##testFile = open(r"D:\Codes\Python\text files\text1.txt", "w")
##testFile.write("Michael Dave Sumang in a path revised")
##testFile.close()

#Specific path Writing(Per Line)
##testFile = open(r"D:\Codes\Python\text files\text1.txt", "w")
##testFile.write("Michael Dave Sumang in a path revised\n")
##testFile.write("Michael Dave Sumang in a path revised 2\n")
##testFile.write("Michael Dave Sumang in a path revised 3\n")
##testFile.close()

#Specifc path Writing(Per Line + Input)
##name = input("Enter a name: ")
##testFile = open(r"D:\Codes\Python\text files\text1.txt", "w")
##testFile.write(name+"\n")
##testFile.close()

#Specifc path Appending(Per Line + Input)
##name = input("Enter a name: ")
##testFile = open(r"D:\Codes\Python\text files\text1.txt", "a")
##testFile.write(name+"\n")
##testFile.close()

##n1 = float(input("Enter a number: "))
##n2 = float(input("Enter a number: "))
##n3 = float(input("Enter a number: "))
##testFile = open(r"D:\Codes\Python\text files\text2.txt", "w")
##testFile.write(str(n1)+"\n")
##testFile.write(str(n2)+"\n")
##testFile.write(str(n3)+"\n")
##testFile.close()


#Reading and Printing
##testFile = open(r"D:\Codes\Python\text files\text1.txt", "r")
##x = testFile.read()
##testFile.close()
##print(x)

#Reading and Printing(Per Line)
##testFile = open(r"D:\Codes\Python\text files\text2.txt", "r")
##x = testFile.readline()
##y = testFile.readline()
##z = testFile.readline()
##testFile.close()
##print(x)
##print(y)
##print(z)

#Reading and Printing(Per Line)(String to integers)
##testFile = open(r"D:\Codes\Python\text files\text2.txt", "r")
##n1 = testFile.readline()
##n2 = testFile.readline()
##n3 = testFile.readline()
##testFile.close()
##sN1 = float(n1.rstrip("\n"))
##sN2 = float(n2.rstrip("\n"))
##sN3 = float(n3.rstrip("\n"))
##x = sN1 + sN2 + sN3
##print(n1)
##print(n2)
##print(n3)
##print()
##print(sN1)
##print(sN2)
##print(sN3)
##print()
##print(x)

##testFile = open(r"D:\Codes\Python\text files\text2.txt", "r")
##n1 = testFile.readline()
##n2 = testFile.readline()
##n3 = testFile.readline()
##testFile.close()
##sN1 = float(n1)
##sN2 = float(n2)
##sN3 = float(n3)
##x = sN1 + sN2 + sN3
##print(n1)
##print(n2)
##print(n3)
##print()
##print(sN1)
##print(sN2)
##print(sN3)
##print()
##print(x)
